name: Engine 95
favicon: null
layout_spectrum: 0.16579
typography_spectrum: 0.07345
title: Engine 59
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ece0a6'
    - '#540302'
    - '#981211'
    - '#609171'
    - '#b0aa7a'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
